MyBlog/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult SendEmail()
        {

            return View();
        }

        [HttpPost]
        public ActionResult SendEmail(EmailForm emailForm)
        {
            if (ModelState.IsValid)
            {

                SmtpClient client = new SmtpClient();
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.EnableSsl = true;
                client.Host = "smtp.gmail.com";
                client.Port = 587;

                // setup Smtp authentication
                System.Net.NetworkCredential credentials =
                    new System.Net.NetworkCredential("myzwirkablog", "zwirkasuperswinka");

                client.UseDefaultCredentials = false;
                client.Credentials = credentials;

                MailMessage msg = new MailMessage();
                msg.From = new MailAddress(emailForm.EmailSender);
                msg.To.Add(new MailAddress("hane.aga@gmail.com"));

                msg.Subject = emailForm.Subject;
                msg.IsBodyHtml = true;
                msg.Body = string.Format("<html><head></head><body><table><tr><td>Adresat: </td><td>"+ emailForm.EmailSender + "</td></tr><tr><td>" + emailForm.Content + "</td></tr></table></body>");
                try
                {
                    client.Send(msg);
                    ViewBag.Status = true;
                    ViewBag.Message = "Dziękuję za wiadomość. E-mail został wysłany!";
                }
                catch
                {
                    ViewBag.Status = false;
                    ViewBag.Message = "Wadimość nie została wysłana! Coś poszło nie tak:( Sprawdź konfigurację";
                }
            }
            else
            {
                ViewBag.Status = false;
                ViewBag.Message = "Nie udało się odczytać formularza, proszę sprawdź dane.";
            }

            return View();
        }
    }
}

MyBlog/Views/Shared/_AddCommentForm.cshtml
@model MyBlog.Models.CommentForNote


@using (Html.BeginForm("AddComment", "Note", new { NoteId = @Model.NoteId, UserId = @Model.UserId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <fieldset class="form-group">
        <label for="exampleTextarea">Dodaj komentarz:</label>
        @Html.TextAreaFor(n => n.Content, new {@class = "form-control"})
    </fieldset>
    <input type="submit" value="Dodaj" class="btn btn-primary"/>

}

MyBlog/Views/Shared/_IsAdded.cshtml
@if (ViewBag.Status != null && ViewBag.Message != null)
{
    <div id="message">
        @if (ViewBag.Status == true)
        {
        <div class="alert alert-success" role="alert">@ViewBag.Message</div>
        }
        else
        {
        <div class="alert alert-danger" role="alert">@ViewBag.Message</div>
        }
    </div>
}
else
{
    <div id="message" style="display: none"></div>
}

MyBlog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>_Layout</title>

    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    @*fix na to by zawartosc nie chowala sie pod menu*@
    <link href="~/Content/starter-template.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    @RenderSection("ScriptsHeader", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Blog", "Index", "Home")</li>
                    @if (ViewContext.HttpContext.User.IsInRole("Admin") || ViewContext.HttpContext.User.IsInRole("Editor"))
                    {
                        <li>@Html.ActionLink("Dodaj wpis", "AddNote", "Admin")</li>
                        <li>@Html.ActionLink("Zarządzaj", "Index", "Admin")</li>
                    }
                    
                    <li>@Html.ActionLink("Kontakt", "SendEmail", "Contact")</li>
                </ul>
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Witaj " + User.Identity.GetUserName() + "!", "Index", "Home", routeValues: null, htmlAttributes: new { title = "Manage" })
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a></li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Rejestracja", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("Logowanie", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    </ul>
                }

            </div>
        </div>
    </nav>
<div class="container">
   
    @RenderBody()
</div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/scripts/jquery-2.2.3.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/scripts/bootstrap.min.js"></script>
</body>
</html>